""" gmail_filter_generator.py --

 UI generated by GUI Builder Build 146 on 2019-08-13 13:13:40 from:
    D:/204370/program/python/Gmail_Filter_Generator/python-2.7.13/gmail_filter_generator.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from gmail_filter_generator_ui import Gmail_filter_generator

# BEGIN USER CODE global

# END USER CODE global

class CustomGmail_filter_generator(Gmail_filter_generator):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _btn_add_command --
    #
    # Callback to handle _btn_add widget option -command
    def _btn_add_command(self, *args):
        pass

    # _btn_export_command --
    #
    # Callback to handle _btn_export widget option -command
    def _btn_export_command(self, *args):
        pass

    # _btn_help_command --
    #
    # Callback to handle _btn_help widget option -command
    def _btn_help_command(self, *args):
        pass

    # _btn_load_command --
    #
    # Callback to handle _btn_load widget option -command
    def _btn_load_command(self, *args):
        pass

    # _listbox_email_xscrollcommand --
    #
    # Callback to handle _listbox_email widget option -xscrollcommand
    def _listbox_email_xscrollcommand(self, *args):
        pass

    # _scrollbar_1_command --
    #
    # Callback to handle _scrollbar_1 widget option -command
    def _scrollbar_1_command(self, *args):
        pass

    # _txt_email_invalidcommand --
    #
    # Callback to handle _txt_email widget option -invalidcommand
    def _txt_email_invalidcommand(self, *args):
        pass

    # _txt_email_validatecommand --
    #
    # Callback to handle _txt_email widget option -validatecommand
    def _txt_email_validatecommand(self, *args):
        pass

    # _txt_email_xscrollcommand --
    #
    # Callback to handle _txt_email widget option -xscrollcommand
    def _txt_email_xscrollcommand(self, *args):
        pass

    # _btn_add_email_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _btn_add_email_command(self, *args):
        pass

    # _entry_3_invalidcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_3_invalidcommand(self, *args):
        pass

    # _entry_3_validatecommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_3_validatecommand(self, *args):
        pass

    # _entry_3_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_3_xscrollcommand(self, *args):
        pass

    # _entry_4_invalidcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_4_invalidcommand(self, *args):
        pass

    # _entry_4_validatecommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_4_validatecommand(self, *args):
        pass

    # _entry_4_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_4_xscrollcommand(self, *args):
        pass

    # _listbox_1_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _listbox_1_xscrollcommand(self, *args):
        pass

    # _listbox_1_yscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _listbox_1_yscrollcommand(self, *args):
        pass

    # _listbox_email_yscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _listbox_email_yscrollcommand(self, *args):
        pass

    # _spinbox_1_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spinbox_1_command(self, *args):
        pass

    # _spinbox_1_invalidcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spinbox_1_invalidcommand(self, *args):
        pass

    # _spinbox_1_validatecommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spinbox_1_validatecommand(self, *args):
        pass

    # _spinbox_1_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spinbox_1_xscrollcommand(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomGmail_filter_generator(root)
    root.title('gmail_filter_generator')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
