""" gmail_filter_generator_ui.py --

 UI generated by GUI Builder Build 146 on 2019-08-13 13:13:40 from:
    D:/204370/program/python/Gmail_Filter_Generator/python-2.7.13/gmail_filter_generator.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Gmail_filter_generator(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._labelframe_3 = Tkinter.LabelFrame(root,
            text = "Enter email address to filter",
        )
        self._labelframe_4 = Tkinter.LabelFrame(root,
            text = "Message",
        )
        self._txt_email = Tkinter.Entry(self._labelframe_3,
            width = 0,
        )
        self._btn_add = Tkinter.Button(self._labelframe_3,
            text = "Add",
        )
        self._lbl_status = Tkinter.Label(self._labelframe_4,
            anchor = "nw",
            justify = "left",
            text = "Ready",
        )
        self._listbox_email = Tkinter.Listbox(root,
            height = 0,
            width = 0,
        )
        self._btn_load = Tkinter.Button(root,
            text = "Load Filter",
        )
        self._btn_export = Tkinter.Button(root,
            text = "Save Filter",
        )
        self._btn_help = Tkinter.Button(root,
            text = "Help",
        )
        self._scrollbar_1 = Tkinter.Scrollbar(root,
        )

        # widget commands

        self._txt_email.configure(
            invalidcommand = self._txt_email_invalidcommand
        )
        self._txt_email.configure(
            validatecommand = self._txt_email_validatecommand
        )
        self._txt_email.configure(
            xscrollcommand = self._txt_email_xscrollcommand
        )
        self._btn_add.configure(
            command = self._btn_add_command
        )
        self._listbox_email.configure(
            xscrollcommand = self._listbox_email_xscrollcommand
        )
        self._listbox_email.configure(
            yscrollcommand = self._scrollbar_1.set
        )
        self._btn_load.configure(
            command = self._btn_load_command
        )
        self._btn_export.configure(
            command = self._btn_export_command
        )
        self._btn_help.configure(
            command = self._btn_help_command
        )
        self._scrollbar_1.configure(
            command = self._scrollbar_1_command
        )


        # Geometry Management
        self._labelframe_3.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 6,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_4.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 6,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._txt_email.grid(
            in_    = self._labelframe_3,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._btn_add.grid(
            in_    = self._labelframe_3,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._lbl_status.grid(
            in_    = self._labelframe_4,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._listbox_email.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 5,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._btn_load.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 2,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._btn_export.grid(
            in_    = root,
            column = 3,
            row    = 4,
            columnspan = 2,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._btn_help.grid(
            in_    = root,
            column = 5,
            row    = 4,
            columnspan = 2,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._scrollbar_1.grid(
            in_    = root,
            column = 6,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsw"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 47, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 179, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 29, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 9, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(5, weight = 0, minsize = 95, pad = 0)
        root.grid_columnconfigure(6, weight = 0, minsize = 2, pad = 0)
        self._labelframe_3.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._labelframe_3.grid_columnconfigure(1, weight = 0, minsize = 297, pad = 0)
        self._labelframe_3.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._labelframe_4.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._labelframe_4.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)


